<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_sessions_modified_user' => 
  array (
    'id' => '8147ad56-c08f-419b-d66f-529dba301c56',
    'relationship_name' => 'bhea_sessions_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sessions_created_by' => 
  array (
    'id' => '815dfea8-1fdb-d70d-1ef9-529dbac31263',
    'relationship_name' => 'bhea_sessions_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sessions_activities' => 
  array (
    'id' => '81740118-8ed6-b8dc-4c77-529dbafe4702',
    'relationship_name' => 'bhea_sessions_activities',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sessions',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sessions_assigned_user' => 
  array (
    'id' => '81d96c93-d60b-9a2b-070a-529dba3506c3',
    'relationship_name' => 'bhea_sessions_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sessions_bhea_registrants_1' => 
  array (
    'id' => '96545d04-5842-0656-0788-529dba7c6ee0',
    'relationship_name' => 'bhea_sessions_bhea_registrants_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Registrants',
    'rhs_table' => 'bhea_registrants',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_registrants_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_registrants_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_registrants_1bhea_registrants_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sponsor_bhea_sessions_1' => 
  array (
    'id' => '968f3708-0b86-a9e3-f859-529dba3e2bb1',
    'relationship_name' => 'bhea_sponsor_bhea_sessions_1',
    'lhs_module' => 'Bhea_Sponsor',
    'lhs_table' => 'bhea_sponsor',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sponsor_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_sponsor_bhea_sessions_1bhea_sponsor_ida',
    'join_key_rhs' => 'bhea_sponsor_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_contractors_bhea_sessions_1' => 
  array (
    'id' => '98782768-6874-f00e-5c96-529dba34fcf5',
    'relationship_name' => 'bhea_contractors_bhea_sessions_1',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_contractors_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_contractors_bhea_sessions_1bhea_contractors_ida',
    'join_key_rhs' => 'bhea_contractors_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_sponsorship_types_1' => 
  array (
    'id' => '98cf15de-8f4d-1634-84a5-529dbad0cdbd',
    'relationship_name' => 'bhea_sessions_bhea_sponsorship_types_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_sponsorship_types_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_sponsorship_types_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_sponsorship_types_1bhea_sponsorship_types_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_speakers_1' => 
  array (
    'id' => '99248c9e-90d2-c60b-cbef-529dbac3779a',
    'relationship_name' => 'bhea_sessions_bhea_speakers_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_speakers_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_speakers_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_speakers_1bhea_speakers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sponsorship_bhea_sessions_1' => 
  array (
    'id' => '997a69a6-1f2e-0658-fc02-529dbaec871a',
    'relationship_name' => 'bhea_sponsorship_bhea_sessions_1',
    'lhs_module' => 'Bhea_Sponsorship',
    'lhs_table' => 'bhea_sponsorship',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sponsorship_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_sponsorship_bhea_sessions_1bhea_sponsorship_ida',
    'join_key_rhs' => 'bhea_sponsorship_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sessions_1' => 
  array (
    'id' => '99d1707e-f000-d3a2-5b72-529dba4feaf8',
    'relationship_name' => 'bhea_events_bhea_sessions_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sessions_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'contacts_bhea_sessions_1' => 
  array (
    'id' => '99ee4a4a-4837-366e-03f6-529dbad966ba',
    'relationship_name' => 'contacts_bhea_sessions_1',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'contacts_bhea_sessions_1_c',
    'join_key_lhs' => 'contacts_bhea_sessions_1contacts_ida',
    'join_key_rhs' => 'contacts_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);