<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_sponsorship_types_modified_user' => 
  array (
    'id' => '4489dda6-49f6-99d6-fa80-529ac4e83c51',
    'relationship_name' => 'bhea_sponsorship_types_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sponsorship_types_created_by' => 
  array (
    'id' => '449d381c-7330-a521-89fe-529ac4ffdc3e',
    'relationship_name' => 'bhea_sponsorship_types_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sponsorship_types_assigned_user' => 
  array (
    'id' => '44fb6e2f-e99e-38c8-8360-529ac4a63286',
    'relationship_name' => 'bhea_sponsorship_types_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sponsorship_types_bhea_sessions_1' => 
  array (
    'lhs_module' => 'bhea_Sponsorship_Types',
    'rhs_module' => 'Bhea_Sessions',
    'relationship_type' => 'one-to-one',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_sponsorship_types_bhea_sessions_1',
  ),
  'bhea_sponsorship_types_activities_calls' => 
  array (
    'id' => '44af2b0c-f6a1-1f14-8ce1-529ac4cc902a',
    'relationship_name' => 'bhea_sponsorship_types_activities_calls',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'bhea_Sponsorship_Types',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sponsorship_types_activities_meetings' => 
  array (
    'id' => '44af2b0c-f6a1-1f14-8ce1-529ac4cc902a',
    'relationship_name' => 'bhea_sponsorship_types_activities_meetings',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'bhea_Sponsorship_Types',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sponsorship_types_activities_notes' => 
  array (
    'id' => '44af2b0c-f6a1-1f14-8ce1-529ac4cc902a',
    'relationship_name' => 'bhea_sponsorship_types_activities_notes',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'bhea_Sponsorship_Types',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sponsorship_types_activities_tasks' => 
  array (
    'id' => '44af2b0c-f6a1-1f14-8ce1-529ac4cc902a',
    'relationship_name' => 'bhea_sponsorship_types_activities_tasks',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'bhea_Sponsorship_Types',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sponsorship_types_activities_emails' => 
  array (
    'id' => '44af2b0c-f6a1-1f14-8ce1-529ac4cc902a',
    'relationship_name' => 'bhea_sponsorship_types_activities_emails',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'bhea_Sponsorship_Types',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);