<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_council_memberships_modified_user' => 
  array (
    'id' => '5737beb1-16be-4c42-cb9f-529f07194099',
    'relationship_name' => 'bhea_council_memberships_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_council_memberships_created_by' => 
  array (
    'id' => '575abd76-eec2-c29f-002c-529f07376378',
    'relationship_name' => 'bhea_council_memberships_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_council_memberships_activities' => 
  array (
    'id' => '577be8e9-5306-7544-e70b-529f0772b92a',
    'relationship_name' => 'bhea_council_memberships_activities',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Council_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_council_memberships_assigned_user' => 
  array (
    'id' => '5808afef-f8e4-99d0-2f73-529f074db99e',
    'relationship_name' => 'bhea_council_memberships_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_council_members_bhea_council_memberships_1' => 
  array (
    'id' => '6daf4f05-8553-dd5d-bc07-529f075aefb4',
    'relationship_name' => 'bhea_council_members_bhea_council_memberships_1',
    'lhs_module' => 'Bhea_Council_Members',
    'lhs_table' => 'bhea_council_members',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'id',
    'join_table' => 'bhea_council_members_bhea_council_memberships_1_c',
    'join_key_lhs' => 'bhea_counc8ee0members_ida',
    'join_key_rhs' => 'bhea_counc1877erships_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_member_levels_bhea_council_memberships_1' => 
  array (
    'id' => '6dfc72d4-7b16-43cd-65d6-529f077f61c4',
    'relationship_name' => 'bhea_member_levels_bhea_council_memberships_1',
    'lhs_module' => 'Bhea_member_levels',
    'lhs_table' => 'bhea_member_levels',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'id',
    'join_table' => 'bhea_member_levels_bhea_council_memberships_1_c',
    'join_key_lhs' => 'bhea_membeb00c_levels_ida',
    'join_key_rhs' => 'bhea_membe2a70erships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_member_levels',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_councils_bhea_council_memberships_1' => 
  array (
    'id' => '702fed7d-c0c9-3092-55cf-529f07ab5486',
    'relationship_name' => 'bhea_councils_bhea_council_memberships_1',
    'lhs_module' => 'Bhea_Councils',
    'lhs_table' => 'bhea_councils',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'id',
    'join_table' => 'bhea_councils_bhea_council_memberships_1_c',
    'join_key_lhs' => 'bhea_councils_bhea_council_memberships_1bhea_councils_ida',
    'join_key_rhs' => 'bhea_councdfbferships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_councils',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_council_memberships_bhea_payments_1' => 
  array (
    'id' => '71fe0342-158c-26dc-fa5d-529f070ab698',
    'relationship_name' => 'bhea_council_memberships_bhea_payments_1',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Payments',
    'rhs_table' => 'bhea_payments',
    'rhs_key' => 'id',
    'join_table' => 'bhea_council_memberships_bhea_payments_1_c',
    'join_key_lhs' => 'bhea_counc7982erships_ida',
    'join_key_rhs' => 'bhea_council_memberships_bhea_payments_1bhea_payments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_bhea_council_memberships_1' => 
  array (
    'id' => '727ab0d0-f5b4-6285-c685-529f07abcdb1',
    'relationship_name' => 'accounts_bhea_council_memberships_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bhea_council_memberships_1_c',
    'join_key_lhs' => 'accounts_bhea_council_memberships_1accounts_ida',
    'join_key_rhs' => 'accounts_bhea_council_memberships_1bhea_council_memberships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_council_memberships_opportunities_1' => 
  array (
    'id' => '72ce107a-9212-6f75-c741-529f0730a6fc',
    'relationship_name' => 'bhea_council_memberships_opportunities_1',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'bhea_council_memberships_opportunities_1_c',
    'join_key_lhs' => 'bhea_councc535erships_ida',
    'join_key_rhs' => 'bhea_council_memberships_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);