<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_sponsorship_modified_user' => 
  array (
    'id' => 'd93e2e0a-2cbc-d364-2bcf-529ecc23ef23',
    'relationship_name' => 'bhea_sponsorship_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsorship_created_by' => 
  array (
    'id' => 'd9714978-b1ba-d42f-87b5-529ecc9da0fb',
    'relationship_name' => 'bhea_sponsorship_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsorship_activities' => 
  array (
    'id' => 'd99b561b-64b1-8ce5-6a9c-529ecc178e5d',
    'relationship_name' => 'bhea_sponsorship_activities',
    'lhs_module' => 'Bhea_Sponsorship',
    'lhs_table' => 'bhea_sponsorship',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sponsorship',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsorship_assigned_user' => 
  array (
    'id' => 'da452773-666d-d4ac-01a4-529ecc0bd9ec',
    'relationship_name' => 'bhea_sponsorship_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_events_bhea_sponsorship_1' => 
  array (
    'id' => '84f6028c-62c8-6671-8212-529ecc4ece79',
    'relationship_name' => 'bhea_events_bhea_sponsorship_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsorship_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsorship_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsorship_1bhea_sponsorship_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sponsorship_bhea_sessions_1' => 
  array (
    'id' => 'a27d0b29-14dd-1ac1-b3af-529ecc3ea992',
    'relationship_name' => 'bhea_sponsorship_bhea_sessions_1',
    'lhs_module' => 'Bhea_Sponsorship',
    'lhs_table' => 'bhea_sponsorship',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sponsorship_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_sponsorship_bhea_sessions_1bhea_sponsorship_ida',
    'join_key_rhs' => 'bhea_sponsorship_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sponsorship',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);