<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.1.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
  ),
  'readme' => '',
  'key' => 'Bhea',
  'author' => 'Bhea',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Products',
  'published_date' => '2013-12-01 05:36:17',
  'type' => 'module',
  'version' => 1385876177,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Products',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Bhea_Sponsorship',
      'class' => 'Bhea_Sponsorship',
      'path' => 'modules/Bhea_Sponsorship/Bhea_Sponsorship.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'Bhea_Speakers',
      'class' => 'Bhea_Speakers',
      'path' => 'modules/Bhea_Speakers/Bhea_Speakers.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'Bhea_Sessions',
      'class' => 'Bhea_Sessions',
      'path' => 'modules/Bhea_Sessions/Bhea_Sessions.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'Bhea_Events',
      'class' => 'Bhea_Events',
      'path' => 'modules/Bhea_Events/Bhea_Events.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bhea_events_bugs_Bhea_Events.php',
      'to_module' => 'Bhea_Events',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/bhea_events_bugsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bhea_Sponsorship',
      'to' => 'modules/Bhea_Sponsorship',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bhea_Speakers',
      'to' => 'modules/Bhea_Speakers',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bhea_Sessions',
      'to' => 'modules/Bhea_Sessions',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Bhea_Events',
      'to' => 'modules/Bhea_Events',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'el_EL',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'it_it',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'lt_LT',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'ja_JP',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'ko_KR',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'lv_LV',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'nb_NO',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'nl_NL',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'pl_PL',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'pt_PT',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'ro_RO',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'ru_RU',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'sv_SE',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'tr_TR',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'zh_CN',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'pt_BR',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'ca_ES',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'en_UK',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'sr_RS',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'sk_SK',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'sq_AL',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bugs.php',
      'to_module' => 'Bugs',
      'language' => 'et_EE',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'en_us',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'bg_BG',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'cs_CZ',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'da_DK',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'de_DE',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'el_EL',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'es_ES',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'fr_FR',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'he_IL',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'hu_HU',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'it_it',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'lt_LT',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'ja_JP',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'ko_KR',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'lv_LV',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'nb_NO',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'nl_NL',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'pl_PL',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'pt_PT',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'ro_RO',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'ru_RU',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'sv_SE',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'tr_TR',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'zh_CN',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'pt_BR',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'ca_ES',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'en_UK',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'sr_RS',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'sk_SK',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'sq_AL',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Bhea_Events.php',
      'to_module' => 'Bhea_Events',
      'language' => 'et_EE',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'sidecarsubpanelbaselayout' => 
  array (
    0 => 
    array (
      'from' => 'custom/modulebuilder/builds/Products/SugarModules/clients/base/layouts/subpanels/bhea_events_bugs_Bhea_Events.php',
      'to_module' => 'Bhea_Events',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bhea_events_bugs_Bhea_Events.php',
      'to_module' => 'Bhea_Events',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bhea_events_bugs_Bugs.php',
      'to_module' => 'Bugs',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Bugs' => 'bhea_events_bugs_name',
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/bhea_events_bugs_Bhea_Events.php',
      'to_module' => 'Bhea_Events',
    ),
  ),
  'sidecarsubpanelmobilelayout' => 
  array (
    0 => 
    array (
      'from' => 'custom/modulebuilder/builds/Products/SugarModules/clients/mobile/layouts/subpanels/bhea_events_bugs_Bhea_Events.php',
      'to_module' => 'Bhea_Events',
    ),
  ),
);