<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_events_modified_user' => 
  array (
    'id' => 'b0015aef-b422-b962-6b1f-529dbe97bba6',
    'relationship_name' => 'bhea_events_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_events_created_by' => 
  array (
    'id' => 'b02a1ef7-16bb-eff4-28ab-529dbe240185',
    'relationship_name' => 'bhea_events_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_events_activities' => 
  array (
    'id' => 'b0518f40-43c1-0cfb-4551-529dbe04113f',
    'relationship_name' => 'bhea_events_activities',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Events',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_events_assigned_user' => 
  array (
    'id' => 'b100dbe2-f3a3-038a-5850-529dbee02e60',
    'relationship_name' => 'bhea_events_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_events_bhea_contractors_1' => 
  array (
    'id' => 'cab3d2f0-9002-4735-d327-529dbe4f60c2',
    'relationship_name' => 'bhea_events_bhea_contractors_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_contractors_1_c',
    'join_key_lhs' => 'bhea_events_bhea_contractors_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_contractors_1bhea_contractors_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_speakers_1' => 
  array (
    'id' => 'cadd765c-597c-4bc0-8f42-529dbeb5ac34',
    'relationship_name' => 'bhea_events_bhea_speakers_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_speakers_1_c',
    'join_key_lhs' => 'bhea_events_bhea_speakers_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_speakers_1bhea_speakers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sponsor_1' => 
  array (
    'id' => 'cb815fcf-0dc1-543a-eb5b-529dbe725ef8',
    'relationship_name' => 'bhea_events_bhea_sponsor_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsor',
    'rhs_table' => 'bhea_sponsor',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsor_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsor_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsor_1bhea_sponsor_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_events_1' => 
  array (
    'id' => 'cbd2c5f4-d99a-e843-4624-529dbe4326f1',
    'relationship_name' => 'bhea_events_bhea_events_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_events_1_c',
    'join_key_lhs' => 'bhea_events_bhea_events_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_events_1bhea_events_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => 'ForBhea_events',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sponsorship_types_1' => 
  array (
    'id' => 'cc53c75f-be0f-53cb-55b6-529dbe318cae',
    'relationship_name' => 'bhea_events_bhea_sponsorship_types_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsorship_types_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsorship_types_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsorship_types_1bhea_sponsorship_types_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_opportunities_1' => 
  array (
    'id' => 'ccd71c59-d4be-f3c8-7a03-529dbe343e44',
    'relationship_name' => 'bhea_events_opportunities_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_opportunities_1_c',
    'join_key_lhs' => 'bhea_events_opportunities_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_hotels_bhea_events_1' => 
  array (
    'id' => 'cd5c8abc-0b9e-357c-6603-529dbe49e998',
    'relationship_name' => 'bhea_hotels_bhea_events_1',
    'lhs_module' => 'Bhea_Hotels',
    'lhs_table' => 'bhea_hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'bhea_hotels_bhea_events_1_c',
    'join_key_lhs' => 'bhea_hotels_bhea_events_1bhea_hotels_ida',
    'join_key_rhs' => 'bhea_hotels_bhea_events_1bhea_events_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_campaigns_1' => 
  array (
    'id' => 'cd88cd55-012f-bcc5-ac15-529dbeb99614',
    'relationship_name' => 'bhea_events_campaigns_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Campaigns',
    'rhs_table' => 'campaigns',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_campaigns_1_c',
    'join_key_lhs' => 'bhea_events_campaigns_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_campaigns_1campaigns_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sponsorship_1' => 
  array (
    'id' => 'ce0cacec-6db1-e0bb-97dd-529dbe2a7036',
    'relationship_name' => 'bhea_events_bhea_sponsorship_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsorship_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsorship_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsorship_1bhea_sponsorship_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_registrants_1' => 
  array (
    'id' => 'cf88c992-0ed5-63a7-2c27-529dbe0c7ed5',
    'relationship_name' => 'bhea_events_bhea_registrants_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Registrants',
    'rhs_table' => 'bhea_registrants',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_registrants_1_c',
    'join_key_lhs' => 'bhea_events_bhea_registrants_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_registrants_1bhea_registrants_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sessions_1' => 
  array (
    'id' => 'd07a74af-f93f-5972-8ef8-529dbed806e9',
    'relationship_name' => 'bhea_events_bhea_sessions_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sessions_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'leads_bhea_events_1' => 
  array (
    'id' => 'd0e0e158-3cd5-0fb8-03c3-529dbe3ea1a7',
    'relationship_name' => 'leads_bhea_events_1',
    'lhs_module' => 'Leads',
    'lhs_table' => 'leads',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'leads_bhea_events_1_c',
    'join_key_lhs' => 'leads_bhea_events_1leads_ida',
    'join_key_rhs' => 'leads_bhea_events_1bhea_events_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);