<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_orders_modified_user' => 
  array (
    'id' => 'a4b4fcaf-e2db-66d4-98fc-529ea0a42b32',
    'relationship_name' => 'bhea_orders_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_created_by' => 
  array (
    'id' => 'a4d2d58e-2a7b-eeb1-fe61-529ea0f97bc7',
    'relationship_name' => 'bhea_orders_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_assigned_user' => 
  array (
    'id' => 'a56d258e-8d76-5098-3d2b-529ea0072eb6',
    'relationship_name' => 'bhea_orders_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'accounts_bhea_orders_1' => 
  array (
    'id' => 'ce641ef9-e5d0-c228-bed3-529ea0b0b002',
    'relationship_name' => 'accounts_bhea_orders_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bhea_orders_1_c',
    'join_key_lhs' => 'accounts_bhea_orders_1accounts_ida',
    'join_key_rhs' => 'accounts_bhea_orders_1bhea_orders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_orders_bhea_invoices_1' => 
  array (
    'id' => 'd3797c7c-a0e0-8040-ce49-529ea07f224c',
    'relationship_name' => 'bhea_orders_bhea_invoices_1',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Invoices',
    'rhs_table' => 'bhea_invoices',
    'rhs_key' => 'id',
    'join_table' => 'bhea_orders_bhea_invoices_1_c',
    'join_key_lhs' => 'bhea_orders_bhea_invoices_1bhea_orders_ida',
    'join_key_rhs' => 'bhea_orders_bhea_invoices_1bhea_invoices_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_orders_bhea_payments_1' => 
  array (
    'rhs_label' => 'Payments',
    'lhs_label' => 'Orders',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Orders',
    'rhs_module' => 'Bhea_Payments',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_orders_bhea_payments_1',
  ),
  'bhea_orders_activities_calls' => 
  array (
    'id' => 'a4f210ea-4b01-4e6d-1ad0-529ea0cc61e2',
    'relationship_name' => 'bhea_orders_activities_calls',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_meetings' => 
  array (
    'id' => 'a4f210ea-4b01-4e6d-1ad0-529ea0cc61e2',
    'relationship_name' => 'bhea_orders_activities_meetings',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_notes' => 
  array (
    'id' => 'a4f210ea-4b01-4e6d-1ad0-529ea0cc61e2',
    'relationship_name' => 'bhea_orders_activities_notes',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_tasks' => 
  array (
    'id' => 'a4f210ea-4b01-4e6d-1ad0-529ea0cc61e2',
    'relationship_name' => 'bhea_orders_activities_tasks',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_emails' => 
  array (
    'id' => 'a4f210ea-4b01-4e6d-1ad0-529ea0cc61e2',
    'relationship_name' => 'bhea_orders_activities_emails',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);