<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_contractors_modified_user' => 
  array (
    'id' => '6dd68c02-df01-f5ba-ce90-529ed89506cc',
    'relationship_name' => 'bhea_contractors_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_created_by' => 
  array (
    'id' => '6df0457f-81d1-d3e4-850a-529ed8ce1653',
    'relationship_name' => 'bhea_contractors_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_assigned_user' => 
  array (
    'id' => '6e76b5c0-edf1-c5a8-b84c-529ed88ebb14',
    'relationship_name' => 'bhea_contractors_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_bhea_sessions_1' => 
  array (
    'id' => '88e46304-19dd-481e-9da7-529ed8dd8048',
    'relationship_name' => 'bhea_contractors_bhea_sessions_1',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_contractors_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_contractors_bhea_sessions_1bhea_contractors_ida',
    'join_key_rhs' => 'bhea_contractors_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_contractors',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_contractors_bhea_events_1' => 
  array (
    'rhs_label' => 'Events',
    'lhs_label' => 'Contractors',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Contractors',
    'rhs_module' => 'Bhea_Events',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_contractors_bhea_events_1',
  ),
  'bhea_contractors_activities_calls' => 
  array (
    'id' => '6e0b71a7-009e-4f09-a27e-529ed80e7ebd',
    'relationship_name' => 'bhea_contractors_activities_calls',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_meetings' => 
  array (
    'id' => '6e0b71a7-009e-4f09-a27e-529ed80e7ebd',
    'relationship_name' => 'bhea_contractors_activities_meetings',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_notes' => 
  array (
    'id' => '6e0b71a7-009e-4f09-a27e-529ed80e7ebd',
    'relationship_name' => 'bhea_contractors_activities_notes',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_tasks' => 
  array (
    'id' => '6e0b71a7-009e-4f09-a27e-529ed80e7ebd',
    'relationship_name' => 'bhea_contractors_activities_tasks',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_emails' => 
  array (
    'id' => '6e0b71a7-009e-4f09-a27e-529ed80e7ebd',
    'relationship_name' => 'bhea_contractors_activities_emails',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);